# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1opPkUs0OEtvp6KaiS4WpraWmbkuUrfws
"""

#importing regular expression library
import re

#using re.match
#to find the first occurrence of the letter 'I' in the string
sentence1 = re.match (r'I', 'I am learning text analytics')
print (sentence1)

#using re.match
#to find the first occurrence of the letter 'v' in the string
sentence2 = re.match (r'v', 'I am learning text analytics')
print (sentence2)

#using re.match
#to find the first occurrence of the letter 'am' in the
string
sentence3 = re.match (r'am', 'I am learning text analytics')
print (sentence3)

sentence4 = re.search(r'am', 'I am learning text analytics')
print (sentence4)

sentence5 = re.search(r'am', '''I am learning text analytics
and am enjoying it''')
print (sentence5)

sentence6 = re.findall(r'am', '''I am learning text analytics
and am enjoying it''')
print (sentence6)

sentence7 = re.split(r'and', '''I am learning text analytics and
am enjoying it''')
print (sentence7)

sentence8 = re.split(r'am', '''I am learning text analytics and
am enjoying it''')
print (sentence8)

sentence9 = re.split(r'am', '''I am learning text analytics and
am enjoying it''', maxsplit=1)
print (sentence9)

sentence9 = re.split(r'am', '''I am learning text analytics and am
enjoying it''', maxsplit=2)
print (sentence9)

sentence10 = re.split(r'am', '''I am learning text analytics, I
am enjoying it and I am going to ace it''', maxsplit=3)
print (sentence10)

sentence11 = re.sub(r'I', 'we', '''I like text analytics and I enjoy
learning it''')
print (sentence11)

sentence1 = re.findall (r'.', 'I am learning text analytics')
print (sentence1)
# Each letter is selected including spaces

sentence2 = re.findall (r'\w', '''I am learning
text analytics''')
print (sentence2)
# Each letter is selected excluding spaces

sentence3 = re.findall (r'\w*', '''I am learning text
analytics''')
print (sentence3)
# Each word is selected including spaces

sentence4 = re.findall (r'\w+', '''I am learning text
analyitics''')
print (sentence4)
# Each word is selected excluding spaces

sentence5 = re.findall (r'^\w+', '''I am learning text
analytics''')
print (sentence5)
# First word is selected

sentence6 = re.findall (r'\w+$', '''I am learning text
analytics''')
print (sentence6)
# Last word is selected

sentence7 = re.findall (r'\w\w', '''I am learning text
analytics''')
print (sentence7)
# 2 consecutive characters are selected

sentence8 = re.findall (r'\b\w\w', '''I am learning text
analytics''')
print (sentence8)
# 2 consecutive characters in a string are selected

sentence9 = re.findall (r'@\w+', '''user@text.com.my,
user@analytics.gov.my, user@textanalytics.edu.my''')
print (sentence9)
# Only the first word in the domain name is selected

sentence10 = re.findall (r'@\w+.\w+', '''user@text.com.my,
user@analytics.gov.my, user@textanalytics.edu.my''')
print (sentence10)

sentence11 = re.findall (r'@\w+.\w+.\w+', '''user@text.com.my,
user@analytics.gov.my, user@textanalytics.edu.my''')
print (sentence11)
# The full domain name is selected

sentence12 = re.findall (r'@\w+.(\w+.\w+)', '''user@text.com.my,
user@analytics.gov.my, user@textanalytics.edu.my''')
print (sentence12)

sentence13 = re.findall (r'\d{2}-\d{2}-\d{4}', '''Ahmad BIT(IS)
15-05-2001, Johnny BCS(SE) 20-08-2000''')
print (sentence13)

sentence14 = re.findall (r'\d{2}-\d{2}-(\d{4})', '''Ahmad BIT(IS)
15-05-2001, Johnny BCS(SE) 20-08-2000''')
print (sentence14)

sentence15 = re.findall(
 r'(\d{2}-\d{2}-)\d{2}(\d{2})',
 'Ahmad BIT(IS) 15-05-2001, Johnny BCS(SE) 20-08-2000'
)
dates = [d + y for d, y in sentence15]
print(dates)

sentence16 = re.findall (r'[aeiouAEIOU]\w+', '''I have eight
story books. I often read them in afternoon''')
print (sentence16)
# A sequence that starts with a vowel followed by one or more
# characters are selected

sentence17 = re.findall (r'\b[aeiouAEIOU]\w+', '''I have eight
story books. I often read them in afternoon''')
print (sentence17)

sentence18 = re.findall (r'\b[^aeiouAEIOU\s]\w+', '''I have eight
story books. I often read them in afternoon''')
print (sentence18)
# Only words that start with non-vowels are selected

sentence19 = re.split (r'[;,]', '''I have many story books,
colouring books; I often read them in the afternoon.''')
print (sentence19)

sentence20 = re.split (r'[;,\s]', '''I have many story books,
colouring books; I often read them in the afternoon.''')
print (sentence20)

sentence21 = re.sub (r'[;,]', '.', '''I have many story books,
colouring books; I often read them in the afternoon.''')
print (sentence21)

import re
text1 = "Order number: 24567, Tracking ID: 8934A12, Quantity: 30"

pattern1 = r'\d+'
matches1 = re.findall(pattern1, text1)

print("Exercise 1 Output:")
print("Digits found:", matches1)
print()

text2 = "Welcome! How's your day going? Call me @ 3pm."

pattern2 = r'[^a-zA-Z0-9]'
matches2 = re.findall(pattern2, text2)

print("Exercise 2 Output:")
print("Non-alphanumeric characters:", matches2)
print()

text3 = "Data Science, AI, and Machine Learning. These fields are growing fast."

pattern3 = r'[,.]'
split_text = re.split(pattern3, text3)

print("Exercise 3 Output:")
print("Split text:", split_text)
print()

text4 = "Contact us at support@example.com or info@company.org"

pattern4 = r'\w+@\w+\.\w+'
new_text = re.sub(pattern4, "[HIDDEN]", text4)

print("Exercise 4 Output:")
print("Anonymized text:", new_text)
print()

text5 = "Emails: user@gmail.com, admin@university.edu, info@company.org"

pattern5 = r'@\w+\.(\w+)'
matches5 = re.findall(pattern5, text5)

print("Exercise 5 Output:")
print("Domain types:", matches5)
print()